game:
  levels: 5

level:
  width: 80
  height: 30
  rooms:
    min_width: 3
    min_height: 3
    max_width: 15
    max_height: 7
    generation_attempts: 300
  corridors:
    dead_end_removals: 20

windows:
  head:
    x: 0
    y: 0
    width: 81
    height: 3
  body:
    x: 0
    y: 3
    width: 81
    height: 31
  footer:
    x: 0
    y: 34
    width: 81
    height: 6

